#!/usr/bin/env -S uv run --quiet
# devenv.py - the dev-env image's proxy contract, compared against the account that generates it.
#
#   needs:    a live SSO session, and nothing else:
#
#                 aws sso login --sso-session awsds
#
#   run:      ./aws/devenv.py                 # sandbox, the only account with an interactive image
#             ./aws/devenv.py staging         # another account folder, once one has a dev-env
#   writes:   aws/output/devenv.txt   (untracked - see .gitignore)
#   reads:    s3:GetObject on the account's own state bucket (the egress slice's outputs) with the
#             kms:Decrypt that bucket's CMK requires; sagemaker:DescribeImageVersion, and
#             ecr:BatchGetImage and ecr:GetDownloadUrlForLayer on the registry the image version
#             names, followed by an HTTPS GET of the one presigned URL that returns the image's
#             config blob; and sts:GetCallerIdentity. It never creates, updates or deletes
#             anything, pulls no layer, and runs no terraform.
#   exits:    0 every check passed | 1 a call failed | 2 a check FAILED
#
# Why this script exists. Since 6d decision 8 (2026-09-10) the house image carries the estate's six
# proxy variables as ENV, and NO_PROXY - the list that keeps AWS calls on the VPC endpoints - is a
# LITERAL in images/dev-env/Dockerfile. The list is generated by <account>/egress, so the copy in the
# Dockerfile is dated the moment it is written, and a change on the generating side leaves an image
# that still works. That is the failure this file makes visible; nothing else in the estate can see
# it.
#
# The two divergences are not the same fault, and the report says which is which:
#
#   in the account, missing from the image   the call leaves through the proxy and SUCCEEDS, as a
#                                            public call carrying neither aws:SourceVpc nor
#                                            aws:SourceVpce - the perimeter is gone and nothing
#                                            fails (6d step 8.8 measured exactly this shape)
#   in the image, missing from the account   the call bypasses the proxy toward an endpoint that is
#                                            not there, so it TIMES OUT rather than being refused
#                                            (Lesson 42: a permission failure is a response, a
#                                            network failure is the absence of one)
#
# Where the list is read from. The generating slice's terraform output is the authority, and this
# script reads it out of the slice's state object rather than by running terraform: `aws/` scripts
# are the aws CLI plus the standard library (aws/INDEX.md), and a state read needs no initialised
# working directory, no terraform binary and no module fetch. The bucket and key are the ones
# scripts/gen-backend-hcl.py writes into backend.hcl - awsds-<env>-tfstate, <account>/egress/.
#
# What the registered image carries (DE-5). DE-3 compares the RECIPE with the account, so an image
# built from an older checkout, or registered from an older tag, passes it while the domain serves
# something else. DE-5 reads the bytes SageMaker serves instead: the image version's ContainerImage is
# a digest, the manifest behind that digest names a config blob, and the blob's `Env` is exactly what
# the Dockerfile's ENV baked - no Docker, no buildbox, and none of the buildbox client's own
# `noProxy` injected over the reading (buildbox.md, "Reading an image's own environment"). The blob
# is checked against its own digest before it is believed.
#
# What it cannot see (Lesson 13), so a clean run is not a working space:
#   - Which image a space is RUNNING. A space keeps its own copy of the version number and can name
#     another image entirely - AWS's SageMaker Distribution sits in the same portal picker, and a
#     space created on it has no proxy variables at all (2026-09-12). `describe-app`'s ResourceSpec
#     is that reading, or /opt/awsds-proxy.txt from inside, which only this image writes.
#   - Whether the variables reach a process. `sudo` strips them and needs the image's two files
#     (6d step 3.1); a Code Editor server inherits them from supervisord. Both are readings taken
#     inside a space - docs/plan/runbooks/sg-proxy.md.
#   - Whether a name in the list has an endpoint at all. This compares two lists; ./aws/egress.py
#     is what measures the endpoints themselves.

from __future__ import annotations

import hashlib
import json
import re
import sys
import urllib.error
import urllib.request

from awslib import context, profiles
from awslib.awscli import AwsCli, ErrorLog
from awslib.report import Checks, Report, failed_calls_epilogue, note

OUT_NAME = "devenv.txt"

# Account folder -> (env name token, the profile that reads its state). A copy of
# scripts/tfhygiene/backend.py's PROFILES and ENV_TOKENS, and a deliberate one: aws/ carries its own
# plumbing so a script still runs from a folder with no repository around it (aws/INDEX.md, the
# CloudShell fallback). The authority is that file; a row here that disagrees with it is a defect.
ACCOUNTS = {
    "sandbox": ("sandbox", "awsds-infra-sandbox-1"),
    "staging": ("staging", "awsds-infra-staging"),
    "production": ("prod", "awsds-infra-prod"),
}

DOCKERFILE = "images/dev-env/Dockerfile"
PROBES_VARIABLES = "terraform-live/sandbox/probes/variables.tf"

ARG_LIST_RE = re.compile(r'^ARG NO_PROXY_LIST="(?P<value>[^"]*)"\s*$', re.M)
ARG_PROXY_RE = re.compile(r"^ARG PROXY_URL=(?P<value>\S+)\s*$", re.M)
PROBES_PROXY_RE = re.compile(r'default\s*=\s*"(?P<value>http://proxy\.[^"]+)"')

# How SageMaker records the bytes an image version was registered against: a digest, never a tag
# (INT-17). The registry is the account that holds the repository, which is not this one.
CONTAINER_IMAGE_RE = re.compile(
    r"^(?P<registry>[0-9]+)\.dkr\.ecr\.[a-z0-9-]+\.amazonaws\.com/"
    r"(?P<repository>[^@]+)@(?P<digest>sha256:[0-9a-f]{64})$"
)

# The six the Dockerfile's final ENV sets. Both spellings, because tools disagree on which they read.
PROXY_NAMES = ("http_proxy", "https_proxy", "HTTP_PROXY", "HTTPS_PROXY", "no_proxy", "NO_PROXY")


def fetch(url: str) -> bytes:
    """GET a presigned URL, honouring only the environment's proxy variables.

    On macOS urllib also consults the system proxy configuration, which the aws CLI does not, so
    reading only the environment keeps this download on the same path as the calls around it.
    """
    handler = urllib.request.ProxyHandler(urllib.request.getproxies_environment())
    with urllib.request.build_opener(handler).open(url, timeout=60) as response:
        return response.read()


def digest(value: str) -> str:
    """The first 16 hex of the list's sha256 - what the image writes to /opt/awsds-proxy.txt."""
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:16]


def entries(value: str) -> list:
    """The list as names. Empty in, empty out - never a list holding one empty string."""
    return [item for item in value.split(",") if item]


def main(argv: list) -> int:
    ctx = context.locate(__file__)
    out_path = ctx.out_file(OUT_NAME)
    out_label = ctx.out_label(OUT_NAME)

    account = argv[0] if argv else "sandbox"
    if account not in ACCOUNTS:
        known = ", ".join(sorted(ACCOUNTS))
        note(f"unknown account folder: {account}", f"known: {known}")
        return 2
    env_token, profile = ACCOUNTS[account]

    errors = ErrorLog()
    callers = profiles.preflight([profile], errors, out_label=out_label)
    caller = callers[0]
    cli = AwsCli(profile=profile, region=context.REGION, errors=errors)

    checks = Checks()

    # ---------------------------------------------------------------- what the repository has
    baked = None
    baked_proxy = None
    dockerfile_path = ctx.repo_root / DOCKERFILE
    if ctx.standalone or not dockerfile_path.is_file():
        checks.note(
            "DE-1",
            "the Dockerfile is readable",
            f"{DOCKERFILE} not found - this script is running outside the repository",
        )
    else:
        text = dockerfile_path.read_text(encoding="utf-8")
        matches = ARG_LIST_RE.findall(text)
        proxy_match = ARG_PROXY_RE.search(text)
        baked_proxy = proxy_match.group("value") if proxy_match else None
        if len(matches) != 1:
            checks.fail(
                "DE-1",
                "the Dockerfile declares one NO_PROXY_LIST",
                f'{len(matches)} `ARG NO_PROXY_LIST="..."` line(s) - the list is one literal, on '
                "one line, so a continuation cannot put whitespace inside an entry",
            )
        else:
            baked = matches[0]
            bad = [name for name in entries(baked) if name.strip() != name or " " in name]
            if bad:
                checks.fail(
                    "DE-1",
                    "the Dockerfile declares one NO_PROXY_LIST",
                    f"{len(bad)} entry(ies) carry whitespace, e.g. {bad[0]!r} - an entry with a "
                    "space matches nothing, and the proxy is used for it silently",
                )
            else:
                checks.ok(
                    "DE-1",
                    "the Dockerfile declares one NO_PROXY_LIST",
                    f"{len(entries(baked))} entries, sha256 {digest(baked)}",
                )

    # ------------------------------------------------------------------- what the account has
    live = None
    bucket = f"awsds-{env_token}-tfstate"
    key = f"{account}/egress/terraform.tfstate"
    if caller.live:
        res = cli.run("s3", "cp", f"s3://{bucket}/{key}", "-", tolerate="NoSuchKey|Not Found|404")
        if res.tolerated:
            checks.fail(
                "DE-2",
                "the account's list is readable",
                f"no state object at s3://{bucket}/{key} - {account}/egress has never been applied",
            )
        elif not res.ok:
            checks.fail("DE-2", "the account's list is readable", "the state read failed")
        else:
            try:
                state = json.loads(res.stdout)
            except json.JSONDecodeError as exc:
                state = None
                checks.fail("DE-2", "the account's list is readable", f"state is not JSON: {exc}")
            if state is not None:
                value = (state.get("outputs") or {}).get("no_proxy", {}).get("value")
                if not value:
                    checks.fail(
                        "DE-2",
                        "the account's list is readable",
                        "the state holds no `no_proxy` output: the slice is DOWN (an [E] destroy "
                        f"leaves the object and removes the outputs). `make up ENV={env_token}` "
                        "first - the comparison below is not a divergence, it is an absence",
                    )
                else:
                    live = value
                    checks.ok(
                        "DE-2",
                        "the account's list is readable",
                        f"{len(entries(live))} entries, sha256 {digest(live)}",
                    )
    else:
        checks.fail("DE-2", "the account's list is readable", f"{profile} did not authenticate")

    # ----------------------------------------------------------------------- the divergence
    missing_from_image: list = []
    stale_in_image: list = []
    if baked is not None and live is not None:
        baked_set, live_set = set(entries(baked)), set(entries(live))
        missing_from_image = sorted(live_set - baked_set)
        stale_in_image = sorted(baked_set - live_set)
        if not missing_from_image and not stale_in_image:
            checks.ok(
                "DE-3",
                "the baked list is the account's list",
                f"{len(live_set)} names, both sides sha256 {digest(live)}",
            )
        else:
            checks.fail(
                "DE-3",
                "the baked list is the account's list",
                f"{len(missing_from_image)} name(s) in the account and not in the image, "
                f"{len(stale_in_image)} the other way - section 4 names them",
            )
    else:
        checks.note(
            "DE-3",
            "the baked list is the account's list",
            "not compared - one of the two sides was not read",
        )

    # The proxy URL is a literal in two tracked files and nothing keeps them equal (Lesson 33). The
    # deployed record is a third fact, in Production's private zone, and this check does not reach it.
    probes_path = ctx.repo_root / PROBES_VARIABLES
    if baked_proxy and not ctx.standalone and probes_path.is_file():
        probes_match = PROBES_PROXY_RE.search(probes_path.read_text(encoding="utf-8"))
        expected = probes_match.group("value") if probes_match else None
        if expected is None:
            checks.note("DE-4", "the proxy URL agrees across the repository", "no default found")
        elif expected == baked_proxy:
            checks.ok("DE-4", "the proxy URL agrees across the repository", baked_proxy)
        else:
            checks.fail(
                "DE-4",
                "the proxy URL agrees across the repository",
                f"Dockerfile {baked_proxy} against {PROBES_VARIABLES} {expected}",
            )

    # ------------------------------------------------------- what the registered image carries
    # The latest version is the one read: the slice's version is force-new on `base_image`, so an
    # apply destroys the previous one and there is never a second to choose between.
    image_name = f"awsds-{env_token}-dev-env"
    served: dict = {}
    served_version = None
    served_digest = None
    config_digest = None
    if caller.live:
        res = cli.run(
            "sagemaker",
            "describe-image-version",
            "--image-name",
            image_name,
            "--query",
            "[Version,ContainerImage]",
            "--output",
            "json",
            tolerate="ResourceNotFound",
        )
        match = None
        if res.tolerated:
            checks.note(
                "DE-5",
                "the registered image carries the account's list",
                f"no version of {image_name} is registered in {account}",
            )
        elif res.ok:
            served_version, container_image = json.loads(res.stdout)
            match = CONTAINER_IMAGE_RE.match(container_image or "")
            if match is None:
                checks.fail(
                    "DE-5",
                    "the registered image carries the account's list",
                    f"version {served_version}'s ContainerImage is not a digest reference: "
                    f"{container_image!r}",
                )
        if match is not None:
            registry, repository = match.group("registry"), match.group("repository")
            served_digest = match.group("digest")
            where = ("--registry-id", registry, "--repository-name", repository)
            manifest_res = cli.run(
                "ecr",
                "batch-get-image",
                *where,
                "--image-ids",
                f"imageDigest={served_digest}",
                "--query",
                "images[0].imageManifest",
                "--output",
                "text",
            )
            if manifest_res.ok:
                config_digest = json.loads(manifest_res.stdout)["config"]["digest"]
                url_res = cli.run(
                    "ecr",
                    "get-download-url-for-layer",
                    *where,
                    "--layer-digest",
                    config_digest,
                    "--query",
                    "downloadUrl",
                    "--output",
                    "text",
                )
                raw = None
                if url_res.ok:
                    try:
                        raw = fetch(url_res.stdout)
                    except (urllib.error.URLError, TimeoutError) as exc:
                        errors.add(("GET", "<presigned config blob URL>"), str(exc))
                if raw is not None:
                    if f"sha256:{hashlib.sha256(raw).hexdigest()}" != config_digest:
                        checks.fail(
                            "DE-5",
                            "the registered image carries the account's list",
                            f"the downloaded config blob does not hash to {config_digest} - "
                            "not the image the manifest names, so nothing in it is believed",
                        )
                    else:
                        env = json.loads(raw).get("config", {}).get("Env") or []
                        for name, _, value in (item.partition("=") for item in env):
                            if name in PROXY_NAMES:
                                served[name] = value

        decided = any(row.split("\t")[1] == "DE-5" for row in checks.rows)
        if config_digest is not None and served_digest is not None and not decided:
            absent = [name for name in PROXY_NAMES if name not in served]
            served_list = served.get("NO_PROXY", "")
            reference, against = (
                (live, "the account's") if live is not None else (baked, "the Dockerfile's")
            )
            if absent:
                checks.fail(
                    "DE-5",
                    "the registered image carries the account's list",
                    f"version {served_version} bakes no {', '.join(absent)} - a space on it "
                    "reaches no internet name, and an AWS call with no bypass list leaves the "
                    "perimeter",
                )
            elif served.get("no_proxy") != served_list:
                checks.fail(
                    "DE-5",
                    "the registered image carries the account's list",
                    f"version {served_version} bakes no_proxy and NO_PROXY differently - a tool "
                    "reading the lowercase spelling gets another perimeter",
                )
            elif baked_proxy and any(served[n] != baked_proxy for n in PROXY_NAMES[:4]):
                checks.fail(
                    "DE-5",
                    "the registered image carries the account's list",
                    f"version {served_version} bakes a proxy URL other than the Dockerfile's "
                    f"{baked_proxy}",
                )
            elif reference is None:
                checks.note(
                    "DE-5",
                    "the registered image carries the account's list",
                    f"version {served_version}: {len(entries(served_list))} names, sha256 "
                    f"{digest(served_list)} - neither side to compare it with was read",
                )
            elif set(entries(served_list)) != set(entries(reference)):
                missing = len(set(entries(reference)) - set(entries(served_list)))
                stale = len(set(entries(served_list)) - set(entries(reference)))
                checks.fail(
                    "DE-5",
                    "the registered image carries the account's list",
                    f"version {served_version} (sha256 {digest(served_list)}) against {against} "
                    f"(sha256 {digest(reference)}): {missing} name(s) the image lacks, {stale} it "
                    "has and should not - DE-3 may pass while the domain serves this",
                )
            else:
                checks.ok(
                    "DE-5",
                    "the registered image carries the account's list",
                    f"version {served_version}, {served_digest[:19]}...: "
                    f"{len(entries(served_list))} names, sha256 {digest(served_list)}",
                )
    else:
        checks.fail(
            "DE-5",
            "the registered image carries the account's list",
            f"{profile} did not authenticate",
        )

    # --------------------------------------------------------------------------- the report
    with open(out_path, "w", encoding="utf-8") as stream:
        rep = Report(stream)

        rep.banner("The dev-env image's proxy contract, against the account that generates it")
        rep.text(f"""generated : {context.utc_stamp()}
account   : {account}   (env token {env_token})
profile   : {profile}
region    : {context.REGION}
produced  : aws/devenv.py   (index: aws/INDEX.md)

SECTIONS
  1. What was compared, and as whom
  2. The account's list, from {account}/egress's state
  3. What the Dockerfile carries
  4. The divergence, name by name
  5. What the registered image carries
  6. Checks
  7. Calls that failed

HOW TO READ THIS FILE
  - A NAME IN THE ACCOUNT AND NOT IN THE IMAGE is the dangerous half: the call leaves
    through the proxy and succeeds, as a public call with neither aws:SourceVpc nor
    aws:SourceVpce. Nothing fails, and the perimeter is gone for that name.
  - A NAME IN THE IMAGE AND NOT IN THE ACCOUNT times out instead: the space bypasses
    the proxy toward an endpoint that is not there, and gets silence rather than a
    refusal (Lesson 42).
  - AN EMPTY `no_proxy` OUTPUT IS THE SESSION BEING DOWN, not a divergence. egress/ is
    [E]; a destroy leaves the state object and removes its outputs.
  - DE-3 COMPARES THE RECIPE; DE-5 READS THE BYTES. An image built from an older
    checkout, or registered from an older tag, passes DE-3 while the domain serves
    something else. Section 5 is the registered image's own baked Env, read from the
    registry by digest and checked against the config blob's own digest.
  - NEITHER SAYS WHICH IMAGE A SPACE RUNS. A space keeps its own version number and can
    name AWS's SageMaker Distribution instead, which bakes no proxy at all. Read
    `describe-app`'s ResourceSpec, or /opt/awsds-proxy.txt inside the space.
  - The repair for any divergence is the chain in docs/plan/runbooks/dev-env.md E:
    edit the Dockerfile, rebuild, push a new tag, bump image_tag, re-attach, restart.

This file is not versioned (aws/output/ is in .gitignore). Regenerate it rather than
trusting a stale copy.""")

        rep.h1("1. What was compared, and as whom")
        rep.tabulate(
            [
                "WHAT\tWHERE",
                f"the account's list\ts3://{bucket}/{key} -> outputs.no_proxy",
                f"the baked list\t{DOCKERFILE} -> ARG NO_PROXY_LIST",
                f"the served list\t{image_name}'s latest version -> ContainerImage -> config Env",
                f"caller\t{caller.arn or '(failed)'}",
            ]
        )

        rep.h1(f"2. The account's list, from {account}/egress's state")
        if live is None:
            rep.text("Not read - see the checks in section 6.")
        else:
            rep.text(f"{len(entries(live))} entries, sha256 {digest(live)}\n")
            rep.tabulate(["NAME"] + entries(live))

        rep.h1("3. What the Dockerfile carries")
        if baked is None:
            rep.text("Not read - see the checks in section 6.")
        else:
            rep.text(f"""{len(entries(baked))} entries, sha256 {digest(baked)}
proxy URL : {baked_proxy or "(not found)"}

The digest above is what a space's /opt/awsds-proxy.txt prints when it is running an
image built from this Dockerfile. Section 5 reads the same digest out of the image the
registry actually holds.""")

        rep.h1("4. The divergence, name by name")
        if baked is None or live is None:
            rep.text("Not compared - one of the two sides was not read.")
        elif not missing_from_image and not stale_in_image:
            rep.text("None. The Dockerfile's literal is the account's current list.")
        else:
            rep.text(f"""in the account, missing from the image : {len(missing_from_image)}
in the image, missing from the account : {len(stale_in_image)}
""")
            rep.tabulate(
                ["NAME\tWHERE IT IS\tWHAT IT DOES TODAY"]
                + [
                    f"{name}\taccount only\tleaves through the proxy, no aws:SourceVpce"
                    for name in missing_from_image
                ]
                + [
                    f"{name}\timage only\tbypasses the proxy toward an absent endpoint: a timeout"
                    for name in stale_in_image
                ]
            )

        rep.h1("5. What the registered image carries")
        if config_digest is None or not served:
            rep.text("Not read - see the checks in section 6.")
        else:
            served_list = served.get("NO_PROXY", "")
            rep.tabulate(
                [
                    "WHAT\tVALUE",
                    f"image version\t{image_name} {served_version}",
                    f"served digest\t{served_digest}",
                    f"config blob\t{config_digest}  (hash checked)",
                    f"proxy URL\t{served.get('HTTPS_PROXY', '(absent)')}",
                    f"NO_PROXY\t{len(entries(served_list))} entries, sha256 {digest(served_list)}",
                ]
            )

        rep.h1("6. Checks")
        rep.checks_table(checks)

        rep.h1("7. Calls that failed")
        failed_calls_epilogue(rep, errors)

    n_fail = checks.n_fail()
    note(
        f"wrote {out_label}",
        f"checks: {len(checks.rows) - n_fail} passed or noted, {n_fail} FAILED"
        if n_fail
        else "all checks passed",
    )
    if n_fail:
        return 2
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
