#!/usr/bin/env bash
# Generate a slice's backend.hcl - Stage 2 step 2.5.
#
#   ./scripts/gen-backend-hcl.sh <account-folder> <slice>
#   ./scripts/gen-backend-hcl.sh production pki
#
# WHY THIS FILE IS GENERATED AND NOT WRITTEN. A `backend` block cannot interpolate anything -
# no var, no local - so the bucket, the key and the REGION have to be literals somewhere.
# docs/plan/architecture.md forbids region literals in .tf files, and step 9's check greps for them.
# Partial backend configuration is the reconciliation: `backend "s3" {}` stays in providers.tf
# and the literals live in a per-slice backend.hcl, which is not a .tf file and is gitignored.
# This script is the ONLY place that knows how to build one - step 8's Makefile calls it rather
# than growing a second copy (Lesson 14: two mechanisms for one file is a defect waiting).
#
# It writes a file. It makes no AWS call, and it does not create the bucket it names - that is
# the bootstrap slice's job, and until that slice has applied, `terraform init` against the
# output of this script fails with NoSuchBucket. That order is step 2.2's chicken-and-egg, not
# a fault here.
set -uo pipefail
cd "$(dirname "$0")/.."

REGION="us-west-2"          # the one literal, in the one place, for the whole tree

usage() { printf 'usage: %s <account-folder> <slice>\n' "${0##*/}" >&2; exit 2; }
[ $# -eq 2 ] || usage
ACCOUNT="$1"; SLICE="$2"

# The account folder and the <env> NAME TOKEN are two different vocabularies, and there is a
# third - the Environment TAG value - which is different again (docs/plan/conventions.md):
#
#   folder            name token   Environment tag
#   sandbox           sandbox      sandbox
#   development       dev          development
#   data-governance   data         data
#   staging           staging      staging
#   production        prod         production
#   identity          org          org
#
# Only the middle column builds a resource name. Conflating it with the first produces
# `awsds-production-tfstate`, a bucket nobody created; conflating it with the third produces
# `awsds-development-tfstate`, the same failure spelled differently.
case "$ACCOUNT" in
  sandbox)         ENV_TOKEN="sandbox" ;;
  development)     ENV_TOKEN="dev" ;;
  data-governance) ENV_TOKEN="data" ;;
  staging)         ENV_TOKEN="staging" ;;
  production)      ENV_TOKEN="prod" ;;
  identity)        ENV_TOKEN="org" ;;
  *) printf 'unknown account folder: %s\n' "$ACCOUNT" >&2; exit 2 ;;
esac

DIR="terraform-live/$ACCOUNT/$SLICE"
[ -d "$DIR" ] || { printf 'no such slice: %s\n' "$DIR" >&2; exit 2; }

BUCKET="awsds-${ENV_TOKEN}-tfstate"
KEY="$ACCOUNT/$SLICE/terraform.tfstate"

# D36, and it is the detail that decides whether D36 is a control or a folder: production/pki/
# holds the internal root CA's private key IN ITS STATE FILE. If it shared the account state
# key, "who can read Production state" and "who can mint a certificate for any internal name"
# would be one permission. Both keys are created by production/bootstrap/ (step 3.4) - a key
# the pki/ slice created could not encrypt the backend that has to exist before it applies.
KMS_ALIAS="alias/awsds-${ENV_TOKEN}-tfstate"
if [ "$ACCOUNT" = "production" ] && [ "$SLICE" = "pki" ]; then
  KMS_ALIAS="alias/awsds-prod-tfstate-pki"
fi

cat >"$DIR/backend.hcl" <<EOF
# GENERATED by scripts/gen-backend-hcl.sh - do not edit, and do not commit (.gitignore).
# Regenerate with: ./scripts/gen-backend-hcl.sh $ACCOUNT $SLICE
# Consume with:    terraform init -backend-config=backend.hcl
bucket       = "$BUCKET"
key          = "$KEY"
region       = "$REGION"
kms_key_id   = "$KMS_ALIAS"
encrypt      = true
use_lockfile = true
EOF

printf 'wrote %s\n' "$DIR/backend.hcl"
printf '  bucket %s   key %s   kms %s\n' "$BUCKET" "$KEY" "$KMS_ALIAS"
